### ISSUE TITLE
Definir os tipos de contribuições a comunidade que são válidas

### ISSUE THREAD

**Issue by drgarcia1986** [drgarcia1986/help-somebody#1]
Minhas sugestões:
- Publicar um blogpost (seja em um blog pessoal ou em blogs comunitários, e.g. [pythonclub](http://pythonclub.com.br/) ).
- Organizar ou apresentar um hangout.
- Organizar um evento (e.g. meetup).
- Apresentar uma palestra em algum evento.
- Gravar uma vídeo aula.
- Ministrar um workshop.
- Contribuir com um projeto open-source que pelo menos mais duas pessoas do grupo usam.

O que acham? mais alguma sugestão?

**Comment by mazulo** [comment]
- Contribuir em um projeto open source com código relevante (aka diferente do que apenas editar readmes hahaha)

**Comment by drgarcia1986** [comment]
Boa @mazulo 👍
