### ISSUE TITLE
Prestação de contas (06/2016) primeiro Mês

### ISSUE THREAD

**Issue by drgarcia1986** [drgarcia1986/help-somebody#14]
Srs. esse é o nosso primeiro mês, fico realmente muito feliz com a adesão ao projeto por todos vcs.
O mês virou e com isso chegou a hora de prestar contas.
Como é o primeiro mês e tudo é novo, vamos discutir aqui como iremos fazer.

Minha sugestão, nessa issue colocamos um checkbox com o nome de cada participante e ele check só deve ser marcado quando esse ou tiver feito suas contribuições para a comunidade ou tiver feito alguma contribuição para caridade.

Como é o primeiro mês e começamos no meio dele, eu voto para dar uma afrouxada na meta, porém, é uma sugestão, vcs que vão dizer.

Teremos que colocar um prazo tmb para o acerto, minha sugestão, não colaborou com a comunidade, tem até o dia 15 do próximo mês para ajudar a caridade de alguma forma, caso contrário, ganha um cartão amarelo. 2 amarelos, vermelho (uma punição de 2 meses talvez, não sei).

Diga oq acham e segue a lista de quem se candidatou.
- [x] @drgarcia1986
- [x] @mazulo 
- [x] @leobiscassi 
- [ ] @RuanAragao 
- [x] @gabrielmarcondes 
- [x] @diegoponciano 

Não deixem de sugerir instituições, já existe a issue #8 para isso inclusive.

**Comment by drgarcia1986** [comment]
já tomei a liberdade de marcar o @diegoponciano e o @gabrielmarcondes como meta cumprida (já que entraram em menos de uma semana praticamente)

**Comment by gabrielmarcondes** [comment]
:+1: 
mesmo com o pouco tempo eu tive uma publicação nesse mês, vou fazer o PR

**Comment by drgarcia1986** [comment]
boa @gabrielmarcondes , registra la, se puder, de opiniões sobre o modelo que devemos seguir

**Comment by leobiscassi** [comment]
Oi pessoal, boa noite!
@drgarcia1986 em relação ao @diegoponciano e ao @gabrielmarcondes eu concordo, agora em relação ao período, acho melhor trabalharmos com o mês fechado.
Quando começamos há 17 dias, eu perguntei para você e para o @mazulo se a meta seria válida para esse mês (por causa do tempo curto), vocês me disseram que sim [1] [2] [3] [4], portanto, não acho válido a gente _afrouxar_ a meta, o que estamos tentando evitar com a iniciativa são justamente essas _afrouxadas_, não acha? :grin: 
Por mim, quem não cumpriu, já leva a primeira _"punição"_ esse mês.
Aproveita e me marca aê, eu cumpri a meta :rocket: :rocket: :rocket: 

[1] [https://twitter.com/leobiscassi/status/742857744005353472](https://twitter.com/leobiscassi/status/742857744005353472)
[2] [https://twitter.com/drgarcia1986/status/742864935647117312](https://twitter.com/drgarcia1986/status/742864935647117312)
[3] [https://twitter.com/ericleribertson/status/742867976244867072](https://twitter.com/ericleribertson/status/742867976244867072)
[4] [https://twitter.com/ericleribertson/status/742867976244867072](https://twitter.com/ericleribertson/status/742867976244867072)

**Comment by drgarcia1986** [comment]
Justo! estarei fazendo minha doação nos próximos dias então, de resto, oq achou @leobiscassi ?

**Comment by leobiscassi** [comment]
@drgarcia1986 cara, achei sensacional! fiz meu primeiro hangouts pra falar de alguma coisa esse mês, uma experiência legal, apesar de algumas coisas não terem saído da melhor maneira possível.
eu tinha feito minha primeira contribuição para projetos opensource em maio, a iniciativa foi uma maneira de manter a "chama acesa", hehe. vamos para o próximo mês! :rocket: :rocket: :rocket:

**Comment by drgarcia1986** [comment]
Marquei o @leobiscassi como concluído o desafio esse mês

**Comment by diegoponciano** [comment]
acho justo também, eu entrei meio ciente que não ía conseguir haha.  
aproveitando, nessa minha doação quero contribuir com as PyLadies, se tiverem alguma sugestão ou conhecerem alguma arrecadação que elas tão fazendo, comentem por favor.

**Comment by leobiscassi** [comment]
@diegoponciano cara, eu fiz uma doação para elas esse mês passado, se não me engano, estavam pedindo auxilio para participar do fisl ... dá uma procurada no catarse.

**Comment by diegoponciano** [comment]
aliás, eu entrei antes do mês terminar justamente pq tô procrastinando um esboço de artigo há uns dois meses huahau, agora ou vai ou racha

**Comment by mazulo** [comment]
CARAS CHEGUEI

Mas concordo com o que foi dito aqui. Com o modelo do @drgarcia1986 (que futuramente pode ser automatizado, e já to modelando algo pra isso), e com a replica do @leobiscassi. Quanto as instituições, acho que para início, PyLadies seria bacana. É algo próximo da nossa realidade, e que já conhecemos que estão precisando de um help. Então, simbora :rocket:

**Comment by gabrielmarcondes** [comment]
Caros, eu tava pensando em algo pra dar visibilidade à produção. Poderíamos fazer um blog ou planet pra agregar os textos/slides. Aqui fica meio escondido, e como um dos nossos objetivos é ajudar a comunidade, acho legal fazer algo pra aumentar o alcance. A gente continua fazendo o controle aqui, mas mantendo esse blog pra divulgar na comunidade.

**Comment by leobiscassi** [comment]
@gabrielmarcondes quando se trata de postagens, elas já estão sendo feitas em blogs pessoais e/ou colaborativos, a ideia do repositório seria mais para controlar as contribuições de cada um até onde eu entendi ... não acha que seria um trabalho a mais replicar tudo que postarmos em outros lugares para um blog próprio? Isso acabaria se tornando um blog colaborativo igual o pythonclub ...

**Comment by gabrielmarcondes** [comment]
@leobiscassi  concordo que seria um trabalho a mais, mas é que as vezes alguém conhece o Leo, mas não conhece o Diego, e por aí vai; mas se já existem outras iniciativas colaborativas nesse sentido, não precisamos mesmo nos preocupar então

**Comment by leobiscassi** [comment]
@gabrielmarcondes eu vi que você fala sobre python, aqui tem um blog colaborativo legal para participar mano! [https://github.com/pythonclub/pythonclub.github.io](https://github.com/pythonclub/pythonclub.github.io)

**Comment by drgarcia1986** [comment]
Entendi a ideia do @gabrielmarcondes e concordo, acho inclusive que seria um atrativo a mais para quem se candidatar é uma forma de divulgar ainda mais... Podemos começar com algo mais simples, tipo um Twitter e ir evoluindo, oq acham?

**Comment by drgarcia1986** [comment]
Fora que o Twitter ajudaria tmb na prestação de contas

**Comment by gabrielmarcondes** [comment]
@drgarcia1986 a ideia do twitter é excelente. não precisamos tanto assim divulgar os textos, como o @leobiscassi falou, mas pra divulgar a iniciativa e trazer mais gente

**Comment by leobiscassi** [comment]
eu acho a ideia do twitter legal também! :smile:

**Comment by drgarcia1986** [comment]
show, já agilizo isso mais tarde então :+1: o @mazulo está na frente do projeto comigo, pode gerenciar o twitter também (e se mais alguém tiver interesse é só falar)
Sobre a doação para as PyLadies, se alguém souber os caminhos é só jogar na issue #8 , vou colocar la um instituição que me recomendaram que faz resgate e cuida de animais abandonados.

**Comment by leobiscassi** [comment]
@drgarcia1986 @mazulo se precisarem de ajuda com o twitter, também seria um prazer, manolos :grin: :grin: :grin:

**Comment by mazulo** [comment]
Opa, tamo junto, pessoal! A ideia do Twitter foi muito bacana. Eu to falando com uma amiga pra ver se arrumamos uma logozinha, que poderia ser usada no `README` do repositório, e perfil do Twitter.

**Comment by leobiscassi** [comment]
fala galera, como ficou a doação das pessoas que não cumpriram a meta?

**Comment by drgarcia1986** [comment]
opa, estou em divida ainda, pretendo fazer a doação até a segunda semana do próximo mês.
Inclusive amanhã é dia de abrir um issue com a prestação de contas do segundo mês.
@mazulo  e @RuanAragao como está a parte de vcs?

**Comment by leobiscassi** [comment]
ok mano!
esse mês foi corrido pra mim ... tô com uma PR aberta num projeto, mas ainda não consegui finalizar as alterações ... devo doar para alguma instituição também. :smile:

**Comment by leobiscassi** [comment]
como ficou a parada do twitter? se vocês quiserem eu posso correr atrás disso. @drgarcia1986 @mazulo :grin: :grin:

**Comment by drgarcia1986** [comment]
Opa, por favor @leobiscassi, vai ajudar muito 😄

**Comment by leobiscassi** [comment]
ok, vou agilizar isso então ... vi que você criou uma organização, apesar de esse mês eu ter enrolado, acho que tenho mais tempo livre que vocês ... se quiser que eu ajude a organizar a coisa e a divulgar mais, vamos pra cima! :grin: :grin: :grin:

**Comment by leobiscassi** [comment]
@mazulo tua amiga conseguiu ver alguma coisa em relação à logo? se não, vou correr atrás disso também, hehe.

**Comment by diegoponciano** [comment]
Nesse mês q passou eu fiz uma doação pra Bendita Adoção q o @drgarcia1986 comentou aqui, pelo site do vakinha: https://www.vakinha.com.br/vaquinha/ajuda-para-pagar-as-contas-veterinarias-da-bendita-adocao  
Nesse próximo mês eu ainda não sei =/

**Comment by drgarcia1986** [comment]
boa @diegoponciano 👏 
você pode fazer um PR adicionando essa doação no mês em que foi feita ?

**Comment by drgarcia1986** [comment]
@diegoponciano BTW acabei de contribuir tmb e já fiz o PR #21

**Comment by diegoponciano** [comment]
@drgarcia1986 tô criando o PR.
Uma dúvida, tradução no transifex conta como contribuição?

**Comment by drgarcia1986** [comment]
@diegoponciano IMO sim 👍 
@gabrielmarcondes @leobiscassi @mazulo @vmesel concordam ?

**Comment by mazulo** [comment]
@leobiscassi @drgarcia1986 @RuanAragao ainda não fiz minha doação do mês passado, mas essa semana, a partir do dia 5 (quando sai o famoso "faz-me-rir"), vou fazer essa e a desse mês, já que só consegui 1 contribuição esse mês (a viagem atrapalhou um bocado 😲). O D. Garcia vai abrir a issue da prestação de contas, e lá vemos melhor essa parte (até jogando a discussão pra lá).

**Comment by mazulo** [comment]
@drgarcia1986 @diegoponciano @gabrielmarcondes @leobiscassi @mazulo @vmesel agora eu fiquei meio na dúvida, porque contribuições como as que são citadas no `README` do repositório, demandam um bom tempo de preparo. No transífex não lembro se tem como através do nosso perfil nós termos algum report de traduções.

Mas parando pra pensar, creio que possa ser considerado sim. Acho que quem estiver aderindo nessa causa não vá fazer algo como traduzir só 1 string e depois relatar como contribuição hahahah

**Comment by leobiscassi** [comment]
eu concordo com o @mazulo, também acho que pode ser considerado :smile:

**Comment by RuanAragao** [comment]
@leobiscassi @drgarcia1986 @mazulo Olá, estou com uma divida grande. Vou iniciar o processo de quitação das doações esse mês (e de contribuições também). Também me perco muito no processo de acompanhar minhas contribuições fora do github, rs. Assim que eu realizar as doações darei feedback! (-:

**Comment by leobiscassi** [comment]
beleza @ruanaragao :rocket: :rocket: :rocket:

**Comment by leobiscassi** [comment]
Fala galera!
Como estão as doações desse mês 06? :grin:

**Comment by mazulo** [comment]
@leobiscassi eu e o @RuanAragao ainda estamos na dívida. Tive uma surpresa financeira desagradável na semana passada. Mas já to me recuperando. Quando eu chegar em casa essa semana, vou quitar tudo 😎

**Comment by leobiscassi** [comment]
suave @mazulo  :rocket: :rocket: :rocket:

**Comment by leobiscassi** [comment]
e aê galera, alguma novidade? :smile:

**Comment by mazulo** [comment]
@leobiscassi juro que no dia 05 eu deixo essa vida de caloteiro uahauhauhauhauh

**Comment by leobiscassi** [comment]
@mazulo  quero ver hein :eyes:

**Comment by leobiscassi** [comment]
@mazulo :eyes:

**Comment by mazulo** [comment]
@drgarcia1986 @gabrielmarcondes @leobiscassi @RuanAragao @juliarizza dinheiro enfim caiu na conta, e to efetuando as doações hoje 😎 (desse e dos outros meses)

**Comment by leobiscassi** [comment]
@mazulo meu herói! só faltou pagar uma breja pra galera, tá cheio da grana agora ... hahaha. :grin:

**Comment by mazulo** [comment]
@leobiscassi this day is coming hahahahaha 😄

**Comment by leobiscassi** [comment]
@mazulo poxa mano, eu tinha mandado um tutorial pra python brasil, foi selecionado, só que eu não vou poder ir :cry:

**Comment by mazulo** [comment]
@leobiscassi pois vamo começar a organizar pra Python Nordeste do ano que vem, hein 😛 vai ser show!

**Comment by leobiscassi** [comment]
ping @mazulo :eyes:

**Comment by mazulo** [comment]
pong @leobiscassi hahaha PR #38 tá na mão

**Comment by leobiscassi** [comment]
@mazulo muito bom mano! desculpa a pegação no pé, hahaha.
Agora só falta o @RuanAragao 👀

**Comment by mazulo** [comment]
@leobiscassi nada manolo, tem que pegar mesmo hahahaha

Bora lá @RuanAragao 😛
