### ISSUE TITLE
Que tal criarmos uma badge de contributor do Help Somebody?

### ISSUE THREAD

**Issue by vmesel** [drgarcia1986/help-somebody#18]
Acredito que uma badge ajudaria a pessoas aderirem ao Help Somebody e também a mostrarmos que queremos ajudar a comunidade. O que vocês acham disto?

**Comment by drgarcia1986** [comment]
parece bacana, como vc pensaria em fazer isso @vmesel ?

**Comment by vmesel** [comment]
existe um projeto da mozila para isso! Vou procurar e depois reabro o issue!
