### ISSUE TITLE
Prestação de contas (07/2016)

### ISSUE THREAD

**Issue by leobiscassi** [drgarcia1986/help-somebody#23]
Oi pessoal, tomei a liberdade de abrir essa _issue_ para fazermos a prestação de contas do mês que passou (07/2016), aparentemente ninguém conseguiu bater a meta.
- [ ] Diego Garcia
- [x] Patrick Mazulo
- [ ] Ruan Aragão
- [x] Léo Biscassi
- [x] Diego Ponciano
- [x] Gabriel Marcondes
- [x] Vinicius Mesel

A _issue_ [#8](https://github.com/help-somebody/help-somebody/issues/8) continua aberta para a sugestão de instituições.

**Comment by mazulo** [comment]
Mês passado só consegui metade da meta. Esse vês vou tentar dobrar essa meta hahahah
Vou jogar lá na #8 uma instituição que lembrei que seria bacana contribuir.

**Comment by leobiscassi** [comment]
:rocket: :rocket: :rocket:

**Comment by leobiscassi** [comment]
PR [#24](https://github.com/help-somebody/help-somebody/pull/24) registrando a minha doação referente ao mês 07/2016, marquei como concluido o mês 07/2016 para mim.

**Comment by leobiscassi** [comment]
Fala pessoal, as pessoas que eu não marquei como concluídas realmente não contribuiram com nada em 07/2016?
Como estão as doações deste mês? :grin:

**Comment by vmesel** [comment]
Eu trabalho com minha pesquisa todos os dias em uma instituição pública, ela contaria como contribuição?

**Comment by leobiscassi** [comment]
@vmesel então cara, é uma boa pergunta. Ela é um projeto opensource? Tem mais pessoas que usam além de você?
Eu particularmente não considero o meu projeto de pesquisa como contribuição porque ninguém usa ele ainda ... eu considero como contribuição as coisas que eu desenvolvo e contribuo para outros projetos que eu uso dentro da minha pesquisa, um exemplo são as PR abaixo:
- [https://github.com/bioconda/bioconda-recipes/pull/1929](https://github.com/bioconda/bioconda-recipes/pull/1929)
- [https://github.com/bioconda/bioconda-recipes/pull/1804](https://github.com/bioconda/bioconda-recipes/pull/1804)
- [https://github.com/galaxyproject/galaxy/pull/2452](https://github.com/galaxyproject/galaxy/pull/2452)
- [https://github.com/bioconda/bioconda-recipes/pull/1643](https://github.com/bioconda/bioconda-recipes/pull/1643)
- [https://github.com/bgruening/galaxytools/pull/310](https://github.com/bgruening/galaxytools/pull/310)

São projetos maiores que eu uso na minha pesquisa, sacou?

**Comment by vmesel** [comment]
Entendi, como todas as ferramentas de minha pesquisa irão ser liberadas de forma open source ao final dela, acho que não contaria então....

**Comment by leobiscassi** [comment]
@vmesel é, é o mesmo caso da minha então ... rsrsrs

**Comment by mazulo** [comment]
Fala pessoal. No mês 07 (assim como no anterior) só cheguei na metade da meta. Vou estar voltando pra minha cidade essa semana, e chegando lá vou realizar a doação pra ONG de lá (que não tem meios bancários de receber).

**Comment by leobiscassi** [comment]
@mazulo tem alguma forma de comprovar a doação mano? eu particularmente não tenho nenhum problema com isso, mas será que o restante do pessoal concorda?

**Comment by vmesel** [comment]
@mazulo @leobiscassi acho q só postar uma foto aqui na issue já está ótimo! Preciso também achar alguma instituição de caridade para fazer a doação!

**Comment by drgarcia1986** [comment]
fiz metade tmb, vou tentar resolver as pendências o quanto antes

**Comment by mazulo** [comment]
@leobiscassi @vmesel pretendo postar uma foto do comprovante, só editando para apagar o valor ou outra informação sensível. Todos de acordo? 😄

**Comment by gabrielmarcondes** [comment]
acabei de fazer o PR com minha contribuição referente ao mês passado :smile: 

por enquanto o comprovante é só esse email que eles mandaram, quando cair no cartão eu troco por uma imagem mais comprobatória
[email recebido](https://s3-sa-east-1.amazonaws.com/tralha/2016-08-15.png)

**Comment by leobiscassi** [comment]
@mazulo sim sinhô! :grin: :grin: :grin:

**Comment by leobiscassi** [comment]
@gabrielmarcondes já marquei como concluída a tua meta, mano! :rocket:

**Comment by mazulo** [comment]
Rapaz, quando o cara é porreta além de fazer uma doação show dessas, ainda sobre a imagem em um S3 hahaha parabéns @gabrielmarcondes 😄

**Comment by vmesel** [comment]
Agora que eu lembrei, eu tinha organizado um grupy e conta como 2 contribuições! tou salvo deste mês kkkkk

**Comment by leobiscassi** [comment]
@vmesel não tinha me atendado a isso, boa! já te marquei como concluído! :grin: :grin: :grin:

**Comment by leobiscassi** [comment]
e aê galera, alguma novidade? :smile:

**Comment by leobiscassi** [comment]
@drgarcia1986 @mazulo @RuanAragao @diegoponciano :eyes:

**Comment by diegoponciano** [comment]
Ando sumido, acho que vou fazer a de Julho pra uma instituição que ajuda crianças da Uganda, vi linkada no texto do último release do VIM (8.0) e me interessei.  
[http://iccf-holland.org/click5.html](http://iccf-holland.org/click5.html)

O que acham?

**Comment by leobiscassi** [comment]
@diegoponciano por mim tudo bem! Eu também adicionei varias causas no INSTITUTIONS.md aqui no projeto qualquer coisa, hehe. :grin:
