### ISSUE TITLE
Prestação de Contas (08/2016)

### ISSUE THREAD

**Issue by leobiscassi** [drgarcia1986/help-somebody#33]
_Issue_ destinada a prestação de contas do mês 08/2016.
- [ ] Diego Garcia
- [x] Patrick Mazulo
- [ ] Ruan Aragão
- [x] Léo Biscassi
- [ ] Diego Ponciano
- [x] Gabriel Marcondes
- [ ] Vinicius Mesel
- [X] Júlia Rizza

A _issue_ [#8](https://github.com/help-somebody/help-somebody/issues/8) continua aberta para a sugestão de instituições.

**Comment by vmesel** [comment]
Eu não fiz nada neste mês, ao menos que preparar o grupy do mês seguinte conte!

**Comment by leobiscassi** [comment]
@vmesel não, o evento ainda não aconteceu, seria a mesma coisa que eu abrir uma PR, não ter terminado o trabalho e incluir como contribuição. :grin:
