### ISSUE TITLE
Prestação de contas (09/2016)

### ISSUE THREAD

**Issue by leobiscassi** [drgarcia1986/help-somebody#40]
_Issue_ destinada a prestação de contas do mês 09/2016.
- [ ] Diego Garcia
- [ ] Patrick Mazulo
- [ ] Ruan Aragão
- [ ] Léo Biscassi
- [ ] Diego Ponciano
- [x] Gabriel Marcondes
- [ ] Vinicius Mesel
- [x] Júlia Rizza

A _issue_ [#8](https://github.com/help-somebody/help-somebody/issues/8) continua aberta para a sugestão de instituições.

**Comment by mazulo** [comment]
@leobiscassi consegui as informações de mais uma instituição para doações. Vou adicionar no final do dia, e já aproveitar pra mandar minha doação também 😆

**Comment by leobiscassi** [comment]
@mazulo aeeeew :rocket: :rocket: :rocket:

**Comment by leobiscassi** [comment]
Vou fechar a issue das instituições ... acho que agora é só colocar as informações no arquivo lá mesmo, já discutimos o que colocar :grin: :+1:
