### ISSUE TITLE
Sugestão para controle

### ISSUE THREAD

**Issue by leobiscassi** [drgarcia1986/help-somebody#41]
Fala pessoal, bom dia!
@drgarcia1986 o que você acha de organizarmos os participantes do projetos em times na organização "help-somebody" que você criou? Um time em que só as pessoas que administram o repo estariam e um outro time com todos os participantes, mais ou menos como o pessoal do bioconda (https://github.com/orgs/bioconda/teams)[https://github.com/orgs/bioconda/teams] faz?
Ficaria mais fácil na hora de chamar o pessoal para o fechamento das contribuições do mês :grin:

**Comment by drgarcia1986** [comment]
Opa @leobiscassi desculpa a demora para responder (estou muito ausente eu sei e sinto que vai piorar um pouco até pelo menos o começo do ano que vem). Coloquei você como membro da organização, nada mais justo visto que você é o membro mais ativo da iniciativa.

Me diga se foi possível criar os times, se não eu aumento seu poder como membro.

**Comment by leobiscassi** [comment]
@drgarcia1986 tranquilo man! :grin: 
cara, para convidar o restante do pessoal, preciso ser owner ... só consegui adicionar você e o @mazulo

**Comment by drgarcia1986** [comment]
fixed

**Comment by leobiscassi** [comment]
@drgarcia1986 thanks!
