### ISSUE TITLE
Prestação de contas (10/2016)

### ISSUE THREAD

**Issue by mazulo** [drgarcia1986/help-somebody#46]
_Issue_ destinada a prestação de contas do mês 10/2016.
- [ ] Diego Garcia
- [ ] Patrick Mazulo
- [ ] Ruan Aragão
- [ ] Léo Biscassi
- [ ] Diego Ponciano
- [ ] Gabriel Marcondes
- [ ] Vinicius Mesel
- [ ] Júlia Rizza

Se alguém tiver esquecido de mandar o commit, como a data fica registrada, pode mandar ainda hahaha se não, tá na hora de contribuir para as instituições 😄

**Comment by leobiscassi** [comment]
@help-somebody/all  Galera, estou com o tempo meio apertado por conta da finalização da minha dissertação de mestrado nesses meses, mas devo acertar minhas pendências em breve. obrigado pela compreensão.
