### ISSUE TITLE
Reativação do projeto

### ISSUE THREAD

**Issue by leobiscassi** [drgarcia1986/help-somebody#47]
Fala galera, alguém a fim de tentar continuar com a ideia? :grin: 

@mazulo @drgarcia1986 @gabrielmarcondes @diegoponciano @RuanAragao

**Comment by gabrielmarcondes** [comment]
Eu queria muito estar escrevendo regularmente mas não consigo, tanto por falta de tempo quanto por falta de criatividade mesmo :(

Mas desde o início desse projeto eu comecei a fazer doações regulares e isso eu não parei :)

(@mazulo você por aqui!)

**Comment by mazulo** [comment]
Quem diria que alguns anos depois seríamos coworkers hein @gabrielmarcondes hahahah

E @leobiscassi eu topo. To querendo voltar com os posts (e também com as doações).

**Comment by diegoponciano** [comment]
eu topo voltar. eu acho difícil começar a postar, apesar de ter vários rascunhos hahahah, mas quero voltar com as doações.

**Comment by leobiscassi** [comment]
Pô galera, massa então!
Eu vou fechar as issues que estão abertas e são antigas, a partir desse 12/2018 eu vou voltar a gerar as *issues* de prestação de contas então ... :grin: :grin: :grin: 
Começar 2019 bem!
