### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ghost** [drgarcia1986/help-somebody#49]

**Comment by gabrielmarcondes** [comment]
oi @lucasnuic!
Fico feliz que você tenha se disposto a colaborar. Não posso falar pelo resto do pessoal, mas eu tinha completamente me esquecido desse projeto aqui. Nos anos seguintes eu até participei de mais alguns de evento de comunidade mas já faz alguns anos que saí do Brasil e não participo mais (nunca parei de fazer doações, mas não tenho registrado nada aqui mesmo).
Por mim você é mais que bem-vindo a colaborar.

**Comment by gabrielmarcondes** [comment]
@lucasnuic Como esse projeto tá esquecido o pessoal nem deve receber notificação, por isso a demora. Mas a galera é boa, pode ter certeza. Quer que eu te coloque como membro da org?

**Comment by gabrielmarcondes** [comment]
@lucasnuic você pode ajudar do jeito que quiser: pode ser código, pode ser blog, pode ser falar em evento, pode ser doação... qualquer ajuda é válida. Aí pra relatar vc faz um PR pra começar (ou editar) um markdown de cada mês/ano como esse aqui por exemplo https://github.com/help-somebody/help-somebody/blob/master/2016/08.md
