### ISSUE TITLE
Quais as instituições de caridade?

### ISSUE THREAD

**Issue by leobiscassi** [drgarcia1986/help-somebody#8]
Oi pessoal, quais as intituições de caridade que serão inclusas para fazermos as doações do grupo? :smile:

**Comment by drgarcia1986** [comment]
Eu pensei em ser algo dinâmico, ou seja, todo mês alguém poderia abrir um issue sugerindo instituições que poderiam receber a doação naquele mês.
O que acham ?
c/c @mazulo @RuanAragao

**Comment by leobiscassi** [comment]
hum ... eu concordo!
é bom gerarmos uma rotatividade também, os membros que não cumprirem doam para uma instituição diferente a cada mês. :smile:

**Comment by mazulo** [comment]
Acho que a gente poderia fazer um levantamento das instituições e colocar
num arquivo. Daí quem for chegando e conhecer alguma outra, vai inserindo.
Mas ainda assim continuando a rotatividade.

O que acham?

**Comment by drgarcia1986** [comment]
concordo com vcs, e acho legal dar uma liberdade para a pessoa doar para a "causa" que ele mais se identificar, por exemplo, posso doar para uma ONG que resgata animais das ruas, algumas pessoas não se identificam com isso, ok, façam em outra instituição então 😄

**Comment by leobiscassi** [comment]
massa! eu vou procurar levantar algumas instituições então! :smiley:

**Comment by leobiscassi** [comment]
@drgarcia1986 @mazulo e aê, já pesquisaram as instituições que vocês vão doar esse mês!? :grin: :grin: :grin:

**Comment by drgarcia1986** [comment]
Conversei sobre o projeto com a minha esposa e ela me recomendou a a ong [bendita adoção](https://www.facebook.com/benditaadocao/), pareceu bem bacana, vou pesquisar mais sobre e como funciona o esquema de doação.

O @leobiscassi falou sobre as PyLadies, acho uma boa tmb por ser algo do nosso meio.

Postem mais sugestões :smile:

**Comment by leobiscassi** [comment]
@drgarcia1986 o projeto que estava aberto no catarse e eu contribui era esse [aqui](https://www.catarse.me/pyladiesnofisl17), vou perguntar no twitter delas se tem mais projetos abertos.

**Comment by leobiscassi** [comment]
mandei um tweet pro perfil oficial delas falando que gostariamos de incluir os projetos que elas tem / terão em nossas causas e pedi mais informações a respeito :smiley:

**Comment by diegoponciano** [comment]
Falei com elas no telegram, e me responderam que vão abrir um crowdfunding pra ajudar o grupo a ir pra Python Brasil em breve, atualmente o que tem é o catarse da FISL e uma loja de camisetas: http://pyladiesbrasil.iluria.com/index.html  
Nesse mês então vou doar pra alguma ong de adoção de animais

**Comment by leobiscassi** [comment]
massa @diegoponciano ! :grin:

**Comment by mazulo** [comment]
Eu vou tentar falar com o pessoal da [ONG Sete Vidas](https://www.facebook.com/ONG7Vidas/), que fica na minha cidade natal. Estão sempre precisando de ajuda para comprar rações, remédios e suporte para castração dos animais que eles resgatam. Conseguindo o contato, vou guardar os dados para jogarmos no arquivo e ficar registrado as instituições.

**Comment by leobiscassi** [comment]
show @mazulo ! :smile:

**Comment by juliarizza** [comment]
Quando colocar as informações das instituições, é interessante colocar também o local onde a instituição atua, pro caso de colaborar não só com doações em dinheiro.

**Comment by leobiscassi** [comment]
O que vocês acham de seguirmos mais ou menos com essas informações:

Página do projeto (site ou facebook)
Dados bancários (pode ser página de financiamente coletivo)
Cidade / Estado

(?)

**Comment by mazulo** [comment]
@leobiscassi @juliarizza super de acordo!

**Comment by drgarcia1986** [comment]
concordo tmb @juliarizza e @leobiscassi 👍

**Comment by diegoponciano** [comment]
@mazulo chegou a falar com o pessoal da ONG Sete Vidas?

**Comment by mazulo** [comment]
@diegoponciano ainda não. Mas vou falar esse final de semana, que é mais fácil de encontrar eles.

**Comment by leobiscassi** [comment]
@mazulo @drgarcia1986 @juliarizza @diegoponciano @gabrielmarcondes @RuanAragao aê galera, adicionei mais algumas instituições no INSTITUTIONS.md aqui no projeto, caso simpatizem com alguma ... :grin: :grin: :grin:

**Comment by leobiscassi** [comment]
Pessoal, estou fechando essa issue, mas caso tenham novas instituições é só adicionar no arquivo :+1:
